[profile.default]
optimizer_runs = 50000000
src = "src"
out = "out"
libs = ["lib"]
bytecode_hash = "none"

auto_detect_solc = true

[profile.default.fuzz]
runs = 10

[profile.ci.fuzz]
runs = 100000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
